name: Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy via Rsync
        run: rsync -rlDc --delete --filter="P .env" -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_PORT }}" ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_FOLDER }}
      - name: Reset Database & Restart
        run: |
          ssh -p ${{ secrets.DEPLOY_PORT }} -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd ${{ secrets.DEPLOY_FOLDER }} && npx prisma migrate reset --force && (pm2 delete \"${{ secrets.APP_NAME }}\" || true) && pm2 start yarn --name \"${{ secrets.APP_NAME }}\" -- start"
      - name: Zip Artifact
        run: zip -r release.zip * .next
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "release"
          path: release.zip
          if-no-files-found: error
      
